---
apiVersion: v1
kind: ConfigMap
metadata:
    name: wpapp-cm
    labels:
        app: wordpress
data:
    DB_USER: root
    DB_HOST: wpdb-svc.wp.svc.cluster.local # Fully Qualified Domain Name

---
    
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wpapp-deploy    
    labels:
        app: wordpress
    
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wpapp-pod
    
    template:
        metadata:
            name: wpapp-pod
            labels:
                app: wpapp-pod
        spec:
            containers:
            - name: wpapp-container
              image: wordpress:latest
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                    cpu: 200m
                    memory: 32Mi
                limits:
                    memory: 64Mi
              envFrom:
              - configMapRef:
                    name: wpapp-cm
              env:
              - name: DB_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: wp-secret
                        key: MYSQL_PASSWORD
              - name: INSTANCE_IP_ADDRESS
                valueFrom:
                    fieldRef:
                        fieldPath: status.podIP
              ports:
              - name: wpapp-port
                containerPort: 80

    
---

apiVersion: v1
kind: Service
metadata:
    name: wpapp-svc
    labels:
        app: wordpress
spec:
    type: ClusterIP
    selector:
        app: wpapp-pod
    ports:
        - name: wp-svc-port
          port: 80
          targetPort: wpapp-port

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: wpapp-ing
    labels:
        app: wordpress
spec:
    rules:
    - host: wp.167.172.4.78.nip.io
      http:
        paths:
        - path: /
          backend:
            serviceName: wpapp-svc
            servicePort: wp-svc-port



# ---

# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#     name: wpapp-hpa
#     labels:
#         app: northwind

# spec:
#     minReplicas: 1
#     maxReplicas: 4
#     scaleTargetRef:
#         apiVersion: apps/v1
#         kind: Deployment
#         name: wpapp-deploy
#     metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#             type: Utilization
#             averageUtilization: 15
#     - type: Resource
#       resource:
#         name: memory
#         target:
#             type: Utilization
#             averageUtilization: 50        
